
/*****************************************************
* this file is automatically generated at compile time
* do not edit it manually.  changes will be lost
******************************************************/


#include "resourcelist.h"
#include "../utils.h"

INC_FILE( progressbar_empty_png );
INC_FILE( cero_d_png );
INC_FILE( button_large_over_png );
INC_FILE( pegi_18_png );
INC_FILE( button_over_png );
INC_FILE( scrollbar_png );
INC_FILE( esrb_e_png );
INC_FILE( cero_a_png );
INC_FILE( boxLogos_png );
INC_FILE( esrb_t_png );
INC_FILE( scrollbar_arrowdown_over_png );
INC_FILE( esrb_eten_png );
INC_FILE( cero_b_png );
INC_FILE( cero_c_png );
INC_FILE( bg_file_selection_entry_png );
INC_FILE( player3_point_png );
INC_FILE( pegi_12_png );
INC_FILE( bg_file_selection_png );
INC_FILE( boxBorder_png );
INC_FILE( cero_z_png );
INC_FILE( keyboard_key_png );
INC_FILE( keyboard_textbox_png );
INC_FILE( scrollbar_arrowdown_png );
INC_FILE( esrb_m_png );
INC_FILE( keyboard_mediumkey_png );
INC_FILE( esrb_ao_png );
INC_FILE( norating_png );
INC_FILE( button_png );
INC_FILE( nocoverFull_png );
INC_FILE( scrollbar_arrowup_png );
INC_FILE( player1_point_png );
INC_FILE( folder_png );
INC_FILE( pegi_16_png );
INC_FILE( keyboard_largekey_over_png );
INC_FILE( aboutWindow_png );
INC_FILE( progressbar_outline_png );
INC_FILE( bg_options_entry_png );
INC_FILE( scrollbar_box_png );
INC_FILE( esrb_ec_png );
INC_FILE( keyboard_largekey_png );
INC_FILE( filebrowser_textbox_png );
INC_FILE( scrollbar_box_over_png );
INC_FILE( dialogue_box_png );
INC_FILE( pegi_3_png );
INC_FILE( bottomButtonWindow_png );
INC_FILE( progressbar_png );
INC_FILE( scrollbar_arrowup_over_png );
INC_FILE( button_large_png );
INC_FILE( player2_point_png );
INC_FILE( keyboard_key_over_png );
INC_FILE( no_ICON0_png );
INC_FILE( bg_options_png );
INC_FILE( background_png );
INC_FILE( player4_point_png );
INC_FILE( keyboard_mediumkey_over_png );
INC_FILE( pegi_7_png );
INC_FILE( button_over_wav );
INC_FILE( button_click_wav );
INC_FILE( button_click_pcm );
INC_FILE( button_click2_wav );
INC_FILE( button_over_pcm );
INC_FILE( bg_music_ogg );

namespace ResourceList
{

map< string, pair< u8*, u32 > >list;

const map< string, pair< u8*, u32 > > &List()
{
	return list;
}

void BuildList()
{
	list.clear();
	list[ "images/progressbar_empty.png" ] = pair< u8*, u32 >( (u8*)progressbar_empty_png, progressbar_empty_png_size );
	list[ "images/cero_d.png" ] = pair< u8*, u32 >( (u8*)cero_d_png, cero_d_png_size );
	list[ "images/button_large_over.png" ] = pair< u8*, u32 >( (u8*)button_large_over_png, button_large_over_png_size );
	list[ "images/pegi_18.png" ] = pair< u8*, u32 >( (u8*)pegi_18_png, pegi_18_png_size );
	list[ "images/button_over.png" ] = pair< u8*, u32 >( (u8*)button_over_png, button_over_png_size );
	list[ "images/scrollbar.png" ] = pair< u8*, u32 >( (u8*)scrollbar_png, scrollbar_png_size );
	list[ "images/esrb_e.png" ] = pair< u8*, u32 >( (u8*)esrb_e_png, esrb_e_png_size );
	list[ "images/cero_a.png" ] = pair< u8*, u32 >( (u8*)cero_a_png, cero_a_png_size );
	list[ "images/boxLogos.png" ] = pair< u8*, u32 >( (u8*)boxLogos_png, boxLogos_png_size );
	list[ "images/esrb_t.png" ] = pair< u8*, u32 >( (u8*)esrb_t_png, esrb_t_png_size );
	list[ "images/scrollbar_arrowdown_over.png" ] = pair< u8*, u32 >( (u8*)scrollbar_arrowdown_over_png, scrollbar_arrowdown_over_png_size );
	list[ "images/esrb_eten.png" ] = pair< u8*, u32 >( (u8*)esrb_eten_png, esrb_eten_png_size );
	list[ "images/cero_b.png" ] = pair< u8*, u32 >( (u8*)cero_b_png, cero_b_png_size );
	list[ "images/cero_c.png" ] = pair< u8*, u32 >( (u8*)cero_c_png, cero_c_png_size );
	list[ "images/bg_file_selection_entry.png" ] = pair< u8*, u32 >( (u8*)bg_file_selection_entry_png, bg_file_selection_entry_png_size );
	list[ "images/player3_point.png" ] = pair< u8*, u32 >( (u8*)player3_point_png, player3_point_png_size );
	list[ "images/pegi_12.png" ] = pair< u8*, u32 >( (u8*)pegi_12_png, pegi_12_png_size );
	list[ "images/bg_file_selection.png" ] = pair< u8*, u32 >( (u8*)bg_file_selection_png, bg_file_selection_png_size );
	list[ "images/boxBorder.png" ] = pair< u8*, u32 >( (u8*)boxBorder_png, boxBorder_png_size );
	list[ "images/cero_z.png" ] = pair< u8*, u32 >( (u8*)cero_z_png, cero_z_png_size );
	list[ "images/keyboard_key.png" ] = pair< u8*, u32 >( (u8*)keyboard_key_png, keyboard_key_png_size );
	list[ "images/keyboard_textbox.png" ] = pair< u8*, u32 >( (u8*)keyboard_textbox_png, keyboard_textbox_png_size );
	list[ "images/scrollbar_arrowdown.png" ] = pair< u8*, u32 >( (u8*)scrollbar_arrowdown_png, scrollbar_arrowdown_png_size );
	list[ "images/esrb_m.png" ] = pair< u8*, u32 >( (u8*)esrb_m_png, esrb_m_png_size );
	list[ "images/keyboard_mediumkey.png" ] = pair< u8*, u32 >( (u8*)keyboard_mediumkey_png, keyboard_mediumkey_png_size );
	list[ "images/esrb_ao.png" ] = pair< u8*, u32 >( (u8*)esrb_ao_png, esrb_ao_png_size );
	list[ "images/norating.png" ] = pair< u8*, u32 >( (u8*)norating_png, norating_png_size );
	list[ "images/button.png" ] = pair< u8*, u32 >( (u8*)button_png, button_png_size );
	list[ "images/nocoverFull.png" ] = pair< u8*, u32 >( (u8*)nocoverFull_png, nocoverFull_png_size );
	list[ "images/scrollbar_arrowup.png" ] = pair< u8*, u32 >( (u8*)scrollbar_arrowup_png, scrollbar_arrowup_png_size );
	list[ "images/player1_point.png" ] = pair< u8*, u32 >( (u8*)player1_point_png, player1_point_png_size );
	list[ "images/folder.png" ] = pair< u8*, u32 >( (u8*)folder_png, folder_png_size );
	list[ "images/pegi_16.png" ] = pair< u8*, u32 >( (u8*)pegi_16_png, pegi_16_png_size );
	list[ "images/keyboard_largekey_over.png" ] = pair< u8*, u32 >( (u8*)keyboard_largekey_over_png, keyboard_largekey_over_png_size );
	list[ "images/aboutWindow.png" ] = pair< u8*, u32 >( (u8*)aboutWindow_png, aboutWindow_png_size );
	list[ "images/progressbar_outline.png" ] = pair< u8*, u32 >( (u8*)progressbar_outline_png, progressbar_outline_png_size );
	list[ "images/bg_options_entry.png" ] = pair< u8*, u32 >( (u8*)bg_options_entry_png, bg_options_entry_png_size );
	list[ "images/scrollbar_box.png" ] = pair< u8*, u32 >( (u8*)scrollbar_box_png, scrollbar_box_png_size );
	list[ "images/esrb_ec.png" ] = pair< u8*, u32 >( (u8*)esrb_ec_png, esrb_ec_png_size );
	list[ "images/keyboard_largekey.png" ] = pair< u8*, u32 >( (u8*)keyboard_largekey_png, keyboard_largekey_png_size );
	list[ "images/filebrowser_textbox.png" ] = pair< u8*, u32 >( (u8*)filebrowser_textbox_png, filebrowser_textbox_png_size );
	list[ "images/scrollbar_box_over.png" ] = pair< u8*, u32 >( (u8*)scrollbar_box_over_png, scrollbar_box_over_png_size );
	list[ "images/dialogue_box.png" ] = pair< u8*, u32 >( (u8*)dialogue_box_png, dialogue_box_png_size );
	list[ "images/pegi_3.png" ] = pair< u8*, u32 >( (u8*)pegi_3_png, pegi_3_png_size );
	list[ "images/bottomButtonWindow.png" ] = pair< u8*, u32 >( (u8*)bottomButtonWindow_png, bottomButtonWindow_png_size );
	list[ "images/progressbar.png" ] = pair< u8*, u32 >( (u8*)progressbar_png, progressbar_png_size );
	list[ "images/scrollbar_arrowup_over.png" ] = pair< u8*, u32 >( (u8*)scrollbar_arrowup_over_png, scrollbar_arrowup_over_png_size );
	list[ "images/button_large.png" ] = pair< u8*, u32 >( (u8*)button_large_png, button_large_png_size );
	list[ "images/player2_point.png" ] = pair< u8*, u32 >( (u8*)player2_point_png, player2_point_png_size );
	list[ "images/keyboard_key_over.png" ] = pair< u8*, u32 >( (u8*)keyboard_key_over_png, keyboard_key_over_png_size );
	list[ "images/no_ICON0.png" ] = pair< u8*, u32 >( (u8*)no_ICON0_png, no_ICON0_png_size );
	list[ "images/bg_options.png" ] = pair< u8*, u32 >( (u8*)bg_options_png, bg_options_png_size );
	list[ "images/background.png" ] = pair< u8*, u32 >( (u8*)background_png, background_png_size );
	list[ "images/player4_point.png" ] = pair< u8*, u32 >( (u8*)player4_point_png, player4_point_png_size );
	list[ "images/keyboard_mediumkey_over.png" ] = pair< u8*, u32 >( (u8*)keyboard_mediumkey_over_png, keyboard_mediumkey_over_png_size );
	list[ "images/pegi_7.png" ] = pair< u8*, u32 >( (u8*)pegi_7_png, pegi_7_png_size );
	list[ "sounds/button_over.wav" ] = pair< u8*, u32 >( (u8*)button_over_wav, button_over_wav_size );
	list[ "sounds/button_click.wav" ] = pair< u8*, u32 >( (u8*)button_click_wav, button_click_wav_size );
	list[ "sounds/button_click.pcm" ] = pair< u8*, u32 >( (u8*)button_click_pcm, button_click_pcm_size );
	list[ "sounds/button_click2.wav" ] = pair< u8*, u32 >( (u8*)button_click2_wav, button_click2_wav_size );
	list[ "sounds/button_over.pcm" ] = pair< u8*, u32 >( (u8*)button_over_pcm, button_over_pcm_size );
	list[ "sounds/bg_music.ogg" ] = pair< u8*, u32 >( (u8*)bg_music_ogg, bg_music_ogg_size );
}

}

